version: '3.8'

services:
  backend:
    container_name: fastapi_backend
    build:
      context: .
    ports:
      - "8000:8000"
    env_file:
      - ./docker-compose.env
    networks:
      - primary_postgres_db_network

  frontend:
    container_name: fastapi_frontend
    build:
      context: ./frontend_v2
    ports:
      - "80:80"
    depends_on:
      - backend
    env_file:
      - ./docker-compose.env
    networks:
      - primary_postgres_db_network

networks:
  primary_postgres_db_network:
    external: true
