version: '3.8'

services:
  backend:
    container_name: fastapi_backend
    build:
      context: .
    ports:
      - "8000:8000"
    networks:
      - primary_postgres_db_network
      - frontend_backend_network
    env_file:
      - ./docker-compose.env

  frontend:
    container_name: fastapi_frontend
    build:
      context: ./frontend_v2
    ports:
      - "8080:8080"
    depends_on:
      - backend
    networks:
      - primary_postgres_db_network
      - frontend_backend_network
    env_file:
      - ./docker-compose.env

networks:
  primary_postgres_db_network:
    external: true
  frontend_backend_network:
    driver: bridge
