"""Diploma revision

Revision ID: f8945108858d
Revises: 
Create Date: 2025-03-11 13:43:03.522027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8945108858d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='base_schema'
    )
    op.create_index(op.f('ix_base_schema_clients_email'), 'clients', ['email'], unique=True, schema='base_schema')
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='base_schema'
    )
    op.create_table('services',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='base_schema'
    )
    op.create_table('orders',
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('order_date', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['base_schema.clients.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['base_schema.services.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='base_schema'
    )
    op.create_table('reviews',
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('review_date', sa.String(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['base_schema.clients.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['base_schema.services.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='base_schema'
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(length=1024), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('registered_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['base_schema.role.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='base_schema'
    )
    op.create_index(op.f('ix_base_schema_users_email'), 'users', ['email'], unique=True, schema='base_schema')
    op.create_table('payments',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('payment_date', sa.String(), nullable=False),
    sa.Column('payment_method', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['base_schema.orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='base_schema'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payments', schema='base_schema')
    op.drop_index(op.f('ix_base_schema_users_email'), table_name='users', schema='base_schema')
    op.drop_table('users', schema='base_schema')
    op.drop_table('reviews', schema='base_schema')
    op.drop_table('orders', schema='base_schema')
    op.drop_table('services', schema='base_schema')
    op.drop_table('role', schema='base_schema')
    op.drop_index(op.f('ix_base_schema_clients_email'), table_name='clients', schema='base_schema')
    op.drop_table('clients', schema='base_schema')
    # ### end Alembic commands ###
